spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: config-server-dev
server:
  port: 8773
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: test
  application:
    name: config-server-test
server:
  port: 8775
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
